ServiciosTecnicosInformaticos/ServiciosTecnicos.Web/Models/ProductoModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ServiciosTecnicos.Web.Models
{
    public class ProductoModel
    {

        public  int Id { get; set; }
        public  string Descripcion { get; set; }
       /* public double precio { get; set; }*/



    }
}

ServiciosTecnicosInformaticos/ServiciosTecnicos.Web/Controllers/ProductosController.cs
using ServiciosTecnicos.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ServiciosTecnicos.Web.Controllers
{
    public class ProductosController : Controller
    {
        // GET: Productos
        public ActionResult Index()
        {
            var producto1 = new ProductoModel();
            producto1.Id = 1;
            producto1.Descripcion = "Mouses";


            var producto2 = new ProductoModel();
            producto2.Id = 2;
            producto2.Descripcion = "Teclados";

            var producto3 = new ProductoModel();
            producto3.Id = 3;
            producto3.Descripcion = "Discos Duros";

            var listadeproductos = new List<ProductoModel>();
            listadeproductos.Add(producto1);
            listadeproductos.Add(producto2);
            listadeproductos.Add(producto3);

            return View(listadeproductos);
        }
    }
}

ServiciosTecnicosInformaticos/ServiciosTecnicos.Web/Controllers/ServiciosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ServiciosTecnicos.Web.Controllers
{
    public class ServiciosController : Controller
    {
        // GET: Servicios
        public ActionResult Index()
        {
            return View();
        }
    }
}

ServiciosTecnicosInformaticos/ServiciosTecnicos.Web/Views/Productos/Index.cshtml
@model List<ServiciosTecnicos.Web.Models.ProductoModel>
    
@{
    ViewBag.Title = "Index";
}


<h2>Productos</h2>

@foreach (var producto in Model)
{
    <p>
    @producto.Id @producto.Descripcion
    </p>
}

ServiciosTecnicosInformaticos/ServiciosTecnicos.Web/Views/Servicios/Index.cshtml

@{
    ViewBag.Title = "Index";
}

<h2>Servicios Tecnicos Informaticos</h2>


ServiciosTecnicosInformaticos/ServiciosTecnicos.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(" Servicios Tecnicos Informaticos", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        @Html.ActionLink("Inicio" , "Index" , "Servicios")
                    </li>
                    @Html.ActionLink("Lista de Prodcuctos","Index","Productos")

                    <li>
                        
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>